<a href="https://colab.research.google.com/github/abasovmanaf-3267/project_numpy/blob/main/3_Practice_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
### 1. Numpy kitabxanasını np kimi yukleyin  və versiyasını yoxlayın

In [1]:
import numpy as np

In [ ]:
### 2. 0-dan 9-a qədər olan rəqəmlərdən ibarət 1D array yaradın. (Numpy kitaxanasini  arange adin bir method var onun kömeyi ile)


In [84]:
# @title
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
### 3. 3×3 ölçülü, bütün elementləri True olan bir array  yaradın.


In [86]:
arrai=np.arange(0,9)

arrai.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [32]:
### 4 Verilmiş array-da bütün tək rəqəmləri çıxarın.
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

arr[arr%2==1]



array([1, 3, 5, 7, 9])

In [41]:
### 4 Tək rəqəmləri -1 ilə əvəz edin

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

tek=arr%2==1

arr[tek]=-1

arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [64]:
### 5 Verilmiş array-dan yalnız müsbət və cüt rəqəmləri çıxarın, nəticəni tərsinə çevirərək ekrana göstərin.
arr = np.array([-10, -2, 0, 3, 4, 8, 15, -5, 12, 20])

In [77]:
cut=arr%2==0

musbet=arr>=0


umumi=arr[cut & musbet]

umumi[::-1]

array([20, 12,  8,  4,  0])

In [78]:
### 6 Verilmiş array-dan  yalnız cüt indekslərdə yerləşən elementləri çıxarın və onların cəmini hesablayın.


arr = np.array([1, 3, 5, 7, 9, 11, 13, 15])

In [83]:
cut_index=arr[::2]

cut_index.sum()



np.int64(28)

In [87]:
### 7  1-dən 20-yə qədər rəqəmlərdən ibarət array yaradın, sonra yalnız 5-ə və ya 7-yə bölünən rəqəmləri saxlayaraq yeni massiv yaradın.

arr = np.arange(1, 21)
filtered = arr[(arr % 5 == 0) | (arr % 7 == 0)]
print(filtered)
# Çıxış: [ 5  7 10 14 15 20]

[ 5  7 10 14 15 20]
